source 'https://rubygems.org'

gem 'rails', '4.1.6'
gem 'mongoid'
gem 'bson_ext'
gem 'devise'

gem 'sass-rails', '~> 4.0.3'
gem 'bootstrap-sass', '~> 3.2.0'
gem 'slim'

gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'therubyracer', platforms: :ruby
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'puma'

group :development do
  gem 'spring'
  gem 'capistrano-rails'
end

group :test do
  gem 'rspec-rails'
end

